# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the trunk branch
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs python
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Set up flake8
      - name: Set up flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Run linting
      - name: Lint
        run: python -m flake8 .

  tests:
    name: pytest ${{ matrix.os }} @ python${{ matrix.python-version }}
    needs: [flake8]

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu, macos, windows]

    runs-on: ${{ matrix.os }}-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs python
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install poetry
        run: python -m pip install poetry

      # Note that this installs into a separate venv as what we installed poetry into
      - name: Install package as editable with dev deps
        run: python -m poetry install
    
      - name: Run tests
        run: python -m poetry run pytest --import-mode=importlib --vcr-record=none
